application: mazalearn
version: 1
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets
  mime_type: text/css
  expiration: "60s"
  
- url: /(.*\.html)
  static_files: static/\1
  upload: static/(.*\.html)
  mime_type: text/html

- url: /javascript
  static_dir: javascript
  mime_type: text/javascript
  expiration: "60s"

- url: /(.*\.gif)
  static_files: static/images/\1
  upload: static/images/(.*\.gif)
  expiration: "3600s"

- url: /(.*\.apk)
  static_files: static/\1
  upload: static/(.*\.apk)

- url: /(.*\.cmf)
  static_files: static/\1
  upload: static/(.*\.mf)
  mime_type: text/cache-manifest
  expiration: "0s"

- url: /(.*\.mp3)
  static_files: static/audio/\1
  upload: static/audio/(.*\.mp3)
  expiration: "3600s"

- url: /(.*\.jpg)
  static_files: static/images/\1
  upload: static/images/(.*\.jpg)
  expiration: "3600s"
  

- url: /(.*\.png)
  static_files: static/images/\1
  upload: static/images/(.*\.png)
  expiration: "3600s"

- url: /.*
  script: main.py
